theme = "noctis-custom"

[editor]
auto-completion = true
popup-border = "all"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-type", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
